package com.mirage.pocom5debloat;

import java.util.HashMap;
import java.util.Map;

public class DebloatConfig {
    public static final String CONF_PATH = "/data/adb/mirage_pocom5_debloat.conf";

    public final Map<String, Boolean> options = new HashMap<>();

    public DebloatConfig() {
        // Defaults
        options.put("UNLOCK_REAL_BLUR", true);
        options.put("UNLOCK_FREEFORM", true);
        options.put("UNLOCK_SIDEBAR", true);
        options.put("UNLOCK_GAME_TURBO", true);
        options.put("UNLOCK_SOUND_ASSIST", true);
        options.put("LOCK_90HZ_SMOOTHNESS", true);

        options.put("DISABLE_MIUI_ADS", true);
        options.put("DISABLE_ANALYTICS", true);
        options.put("ENABLE_HOSTS_ADBLOCK", true);

        options.put("DEBLOAT_CAROUSEL", true);
        options.put("DEBLOAT_GETAPPS", true);
        options.put("DEBLOAT_MI_BROWSER", true);
        options.put("DEBLOAT_MI_VIDEO", true);
        options.put("DEBLOAT_MI_MUSIC", true);
        options.put("DEBLOAT_CLEANMASTER", true);
        options.put("DEBLOAT_YELLOW_PAGES", true);
        options.put("DEBLOAT_FACEBOOK", true);
        options.put("DEBLOAT_PARTNER_APPS", true);
        options.put("DEBLOAT_GOOGLE_BLOAT", true);
    }

    public void loadFromSystem() {
        String raw = SuHelper.runSu("cat " + CONF_PATH + " 2>/dev/null");
        if (raw.isEmpty() || raw.startsWith("ERROR")) return;

        for (String line : raw.split("\n")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;
            int idx = trimmed.indexOf('=');
            if (idx > 0) {
                String key = trimmed.substring(0, idx).trim();
                String val = trimmed.substring(idx + 1).trim();
                options.put(key, "1".equals(val));
            }
        }
    }

    public boolean saveToSystem() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by POCO M5 Optimizer App\\n");
        for (Map.Entry<String, Boolean> entry : options.entrySet()) {
            sb.append(entry.getKey()).append("=").append(entry.getValue() ? "1" : "0").append("\\n");
        }
        String cmd = "echo -e \"" + sb.toString() + "\" > " + CONF_PATH + " && chmod 0644 " + CONF_PATH;
        String res = SuHelper.runSu(cmd);
        return !res.startsWith("ERROR");
    }

    public boolean get(String key) {
        Boolean val = options.get(key);
        return val != null && val;
    }

    public void set(String key, boolean value) {
        options.put(key, value);
    }
}
